### ISSUE TITLE
Thank you for using our proposed algorithms!

### ISSUE THREAD

**Issue by nanlliu** [Slickytail/stable-diffusion-compositional#2]
Thank you for using our proposed method to compose diffusion models!

We are wondering if you wouldn't mind adding a link to our original repo?

it was cool that you also provide an option for adjusting weights for each prompt!

 🤗 We would also greatly appreciate adding a citation to our paper:

@article{liu2022compositional,
  title={Compositional Visual Generation with Composable Diffusion Models},
  author={Liu, Nan and Li, Shuang and Du, Yilun and Torralba, Antonio and Tenenbaum, Joshua B},
  journal={arXiv preprint arXiv:2206.01714},
  year={2022}
}

**Comment by Slickytail** [comment]
Hi,

Sure, can't believe I forgot to before!! What's the link to your repo?

**Comment by nanlliu** [comment]
https://github.com/energy-based-model/Compositional-Visual-Generation-with-Composable-Diffusion-Models-PyTorch

greatly appreciated! feel free to close this issue anytime!
